import { IntakeFieldDefinition } from "./types";

/**
 * 信息采集字段与《智慧父母测评-v2》Word 文档前段一致（题目编号与选项文案对齐）。
 * 决策人数等旧版字段已从表单移除；历史客户库中对应列可为空。
 */
export const intakeFields: IntakeFieldDefinition[] = [
  {
    key: "wechatNickname",
    label: "1、您的微信昵称",
    type: "text",
    required: true,
    placeholder: "请输入微信昵称",
  },
  {
    key: "phone",
    label: "2、您的手机号是",
    type: "phone",
    required: true,
    placeholder: "请输入 11 位手机号",
  },
  {
    key: "memberStatus",
    label: "3、您是否是帆书APP会员",
    type: "single-select",
    required: true,
    options: [
      { label: "是帆书 365年卡VIP会员（在会期内）", value: "是帆书 365年卡VIP会员（在会期内）" },
      {
        label: "是帆书 付费会员，【非年卡 】或者【已过期】",
        value: "是帆书 付费会员，【非年卡 】或者【已过期】",
      },
      { label: "注册过帆书，但未付费", value: "注册过帆书，但未付费" },
      { label: "不是", value: "不是" },
    ],
  },
  {
    key: "residenceCity",
    label: "4、您长期居住的城市是",
    type: "text",
    required: true,
    placeholder: "例如：上海市",
  },
  {
    key: "gender",
    label: "5、您的性别是",
    type: "single-select",
    required: true,
    options: [
      { label: "女", value: "女" },
      { label: "男", value: "男" },
    ],
  },
  {
    key: "education",
    label: "6、您的最高学历是",
    type: "single-select",
    required: true,
    options: [
      { label: "硕士研究生及以上", value: "硕士研究生及以上" },
      { label: "大学本科", value: "大学本科" },
      { label: "大学专科", value: "大学专科" },
      { label: "中专、高职、高中及以下", value: "中专、高职、高中及以下" },
    ],
  },
  {
    key: "ageRange",
    label: "7、您的年龄段处于？",
    type: "single-select",
    required: true,
    options: [
      { label: "25岁及以下", value: "25岁及以下" },
      { label: "26-30岁", value: "26-30岁" },
      { label: "31-35岁", value: "31-35岁" },
      { label: "36-40岁", value: "36-40岁" },
      { label: "41-45岁", value: "41-45岁" },
      { label: "46-50岁", value: "46-50岁" },
      { label: "51岁及以上", value: "51岁及以上" },
    ],
  },
  {
    key: "childrenCount",
    label: "8、您有几个孩子？",
    type: "single-select",
    required: true,
    options: [
      { label: "1个", value: "1个" },
      { label: "2个", value: "2个" },
      { label: "3个及以上", value: "3个及以上" },
      { label: "0个", value: "0个" },
    ],
  },
  {
    key: "childAgeRanges",
    label: "9、您的孩子在哪个年龄段（可多选）",
    type: "multi-select",
    required: true,
    options: [
      { label: "0-3岁", value: "0-3岁" },
      { label: "4-6岁", value: "4-6岁" },
      { label: "7-9岁", value: "7-9岁" },
      { label: "10-12岁", value: "10-12岁" },
      { label: "13-15岁", value: "13-15岁" },
      { label: "16-18岁", value: "16-18岁" },
      { label: "19岁及以上", value: "19岁及以上" },
    ],
  },
  {
    key: "primaryCaretaker",
    label: "10、日常主要由谁照顾孩子",
    type: "single-select",
    required: true,
    options: [
      { label: "孩子爸爸", value: "孩子爸爸" },
      { label: "孩子妈妈", value: "孩子妈妈" },
      { label: "孩子的爸爸妈妈一起", value: "孩子的爸爸妈妈一起" },
      { label: "孩子的祖辈，爷爷奶奶、姥姥姥爷", value: "孩子的祖辈，爷爷奶奶、姥姥姥爷" },
      { label: "保姆阿姨", value: "保姆阿姨" },
      { label: "其他", value: "其他" },
    ],
  },
  {
    key: "parentingRole",
    label: "11、您的养育角色更接近",
    type: "single-select",
    required: true,
    options: [
      { label: "职场妈妈/爸爸（兼顾工作与育儿）", value: "职场妈妈/爸爸（兼顾工作与育儿）" },
      { label: "全职妈妈/爸爸", value: "全职妈妈/爸爸" },
    ],
  },
  {
    key: "occupationCategory",
    label: "12、您的具体职业是",
    type: "single-select",
    required: true,
    options: [
      {
        label: "公务员/事业单位（综合管理/行政执法/专业技术/医疗/科研/文化等）",
        value: "公务员/事业单位（综合管理/行政执法/专业技术/医疗/科研/文化等）",
      },
      { label: "国有企业（能源/通信/金融/交通等国企）", value: "国有企业（能源/通信/金融/交通等国企）" },
      { label: "服务业（餐饮/零售/物流/旅游等服务行业）", value: "服务业（餐饮/零售/物流/旅游等服务行业）" },
      { label: "教育行业（教师/教培机构/教育科技等教育行业）", value: "教育行业（教师/教培机构/教育科技等教育行业）" },
      { label: "制造业（汽车/电子/纺织/机械/钢铁等制造业）", value: "制造业（汽车/电子/纺织/机械/钢铁等制造业）" },
      { label: "医疗行业（医生/护士/医药研发等医疗相关）", value: "医疗行业（医生/护士/医药研发等医疗相关）" },
      { label: "互联网行业（电商/游戏/社交平台/云计算等互联网相关）", value: "互联网行业（电商/游戏/社交平台/云计算等互联网相关）" },
      { label: "金融行业（银行/证券/保险/互联网金融等相关）", value: "金融行业（银行/证券/保险/互联网金融等相关）" },
      { label: "房地产行业（开发/中介/物业/装修等相关）", value: "房地产行业（开发/中介/物业/装修等相关）" },
      {
        label: "自由职业（自媒体/独立设计师/网约车司机等相关）",
        value: "自由职业（自媒体/独立设计师/网约车司机等相关）",
      },
      { label: "法律行业（律师/法务/公证等相关）", value: "法律行业（律师/法务/公证等相关）" },
      { label: "文化传媒（记者/编辑/影视制作等相关）", value: "文化传媒（记者/编辑/影视制作等相关）" },
      { label: "平台经济（外卖骑手/直播主播/电商店主等相关）", value: "平台经济（外卖骑手/直播主播/电商店主等相关）" },
      {
        label: "科技创新（人工智能/区块链/生物医药等相关）",
        value: "科技创新（人工智能/区块链/生物医药等相关）",
      },
      { label: "珠宝、奢侈品、化妆品行业等相关", value: "珠宝、奢侈品、化妆品行业等相关" },
      { label: "全职妈妈/爸爸", value: "全职妈妈/爸爸" },
      { label: "其他", value: "其他" },
    ],
  },
  {
    key: "occupationDetail",
    label: "职业补充说明（选填）",
    type: "text",
    required: false,
    placeholder: "若选「其他」或需补充岗位信息，可在此填写",
  },
  {
    key: "coreProblem",
    label: "13、请您详细描述：当前最头疼的育儿难题是什么？发生这个问题你在担心什么？",
    type: "textarea",
    required: true,
    placeholder: "请尽量写具体场景与您的担心",
  },
  {
    key: "attemptedActions",
    label: "14、为解决这个难题，您这边做了什么？效果是什么？",
    type: "textarea",
    required: true,
    placeholder: "请描述您已尝试的做法与效果",
  },
  {
    key: "desiredSupport",
    label: "15、您希望在学习期间获得哪些帮助？（可多选）",
    type: "multi-select",
    required: true,
    options: [
      { label: "与我1V1时，针对我的问题，多多指导我，给我建议", value: "与我1V1时，针对我的问题，多多指导我，给我建议" },
      {
        label: "直播课程中，讲师直接解答我的问题（注意：讲师点名时需在场，讲师提问时需回答）",
        value: "直播课程中，讲师直接解答我的问题（注意：讲师点名时需在场，讲师提问时需回答）",
      },
      { label: "如何系统学习？请推荐课程给我，我想付款报名", value: "如何系统学习？请推荐课程给我，我想付款报名" },
      { label: "请提醒我听课，督促我进入直播间", value: "请提醒我听课，督促我进入直播间" },
    ],
  },
];
