import { IntakeFieldDefinition } from "./types";

export const intakeFields: IntakeFieldDefinition[] = [
  {
    key: "wechatNickname",
    label: "您的微信昵称",
    type: "text",
    required: true,
    placeholder: "请输入微信昵称",
  },
  {
    key: "phone",
    label: "您的手机号",
    type: "phone",
    required: true,
    placeholder: "请输入手机号",
  },
  {
    key: "memberStatus",
    label: "您是否是帆书 APP 会员",
    type: "single-select",
    required: true,
    options: [
      { label: "不是", value: "不是" },
      { label: "注册过帆书，但未付费", value: "注册过帆书，但未付费" },
      { label: "是帆书付费会员", value: "是帆书付费会员" },
      { label: "是帆书 365 年卡 VIP 会员（在会员期内）", value: "是帆书 365 年卡 VIP 会员（在会员期内）" },
    ],
  },
  {
    key: "gender",
    label: "您的性别",
    type: "single-select",
    required: true,
    options: [
      { label: "女", value: "女" },
      { label: "男", value: "男" },
    ],
  },
  {
    key: "education",
    label: "您的最高学历",
    type: "single-select",
    required: true,
    options: [
      { label: "中专、高职、高中及以下", value: "中专、高职、高中及以下" },
      { label: "大学专科", value: "大学专科" },
      { label: "大学本科", value: "大学本科" },
      { label: "硕士及以上", value: "硕士及以上" },
    ],
  },
  {
    key: "ageRange",
    label: "您的年龄段",
    type: "single-select",
    required: true,
    options: [
      { label: "31-35岁", value: "31-35岁" },
      { label: "36-40岁", value: "36-40岁" },
      { label: "41-45岁", value: "41-45岁" },
      { label: "46岁及以上", value: "46岁及以上" },
    ],
  },
  {
    key: "childrenCount",
    label: "您有几个孩子",
    type: "single-select",
    required: true,
    options: [
      { label: "0个", value: "0个" },
      { label: "1个", value: "1个" },
      { label: "2个", value: "2个" },
      { label: "3个及以上", value: "3个及以上" },
    ],
  },
  {
    key: "childAgeRanges",
    label: "您的孩子在哪个年龄段（可多选）",
    type: "multi-select",
    required: true,
    options: [
      { label: "0-3岁", value: "0-3岁" },
      { label: "4-6岁", value: "4-6岁" },
      { label: "7-9岁", value: "7-9岁" },
      { label: "10-12岁", value: "10-12岁" },
      { label: "13-15岁", value: "13-15岁" },
      { label: "16-18岁", value: "16-18岁" },
      { label: "19岁及以上", value: "19岁及以上" },
    ],
  },
  {
    key: "decisionMakerCount",
    label: "家庭中主要参与育儿决策的人数",
    type: "single-select",
    required: true,
    options: [
      { label: "1人主导", value: "1人主导" },
      { label: "2人协商", value: "2人协商" },
      { label: "3人及以上参与", value: "3人及以上参与" },
    ],
  },
  {
    key: "primaryCaretaker",
    label: "日常主要由谁照顾孩子",
    type: "single-select",
    required: true,
    options: [
      { label: "孩子妈妈", value: "孩子妈妈" },
      { label: "孩子爸爸", value: "孩子爸爸" },
      { label: "孩子的爸爸妈妈一起", value: "孩子的爸爸妈妈一起" },
      { label: "孩子的祖辈", value: "孩子的祖辈" },
      { label: "其他", value: "其他" },
    ],
  },
  {
    key: "parentingRole",
    label: "您的养育角色更接近",
    type: "single-select",
    required: true,
    options: [
      { label: "全职妈妈/爸爸", value: "全职妈妈/爸爸" },
      { label: "职场妈妈/爸爸（兼顾工作与育儿）", value: "职场妈妈/爸爸（兼顾工作与育儿）" },
      { label: "孩子的祖辈，爷爷奶奶、姥姥姥爷", value: "孩子的祖辈，爷爷奶奶、姥姥姥爷" },
    ],
  },
  {
    key: "occupationCategory",
    label: "您的具体职业类别",
    type: "single-select",
    required: true,
    options: [
      { label: "互联网行业", value: "互联网行业" },
      { label: "服务业", value: "服务业" },
      { label: "医疗行业", value: "医疗行业" },
      { label: "制造业", value: "制造业" },
      { label: "国有企业", value: "国有企业" },
      { label: "全职妈妈/爸爸", value: "全职妈妈/爸爸" },
      { label: "其他", value: "其他" },
    ],
  },
  {
    key: "occupationDetail",
    label: "您的具体职业描述",
    type: "text",
    required: false,
    placeholder: "可补充更具体的职业信息",
  },
  {
    key: "coreProblem",
    label: "请您详细描述：当前最头疼的育儿难题是什么？",
    type: "textarea",
    required: true,
    placeholder: "例如：孩子写作业拖拉、情绪大、沉迷手机、亲子沟通困难等",
  },
  {
    key: "coreConcern",
    label: "发生这个问题你在担心什么？",
    type: "textarea",
    required: true,
    placeholder: "例如：担心学习成绩、亲子关系、孩子性格发展等",
  },
  {
    key: "attemptedActions",
    label: "为解决这个难题，您这边做了什么？",
    type: "textarea",
    required: true,
    placeholder: "例如：讲道理、制定规则、报班、看书、改变沟通方式等",
  },
  {
    key: "attemptedOutcome",
    label: "效果是什么？",
    type: "textarea",
    required: true,
    placeholder: "例如：短期有效、反复、几乎无效等",
  },
  {
    key: "desiredSupport",
    label: "您希望在学习期间获得哪些帮助（可多选）",
    type: "multi-select",
    required: true,
    options: [
      { label: "与我1V1时，针对我的问题，多多指导我，给我建议", value: "1v1指导" },
      { label: "直播课程中，讲师直接解答答疑", value: "直播答疑" },
      { label: "请提醒我听课，督促我进入直播间", value: "提醒听课" },
      { label: "如何系统学习？请推荐课程", value: "课程推荐" },
    ],
  },
];
